app:
  version: "@project.version@"

spring:
  application:
    name: TASKFLOW-SERVICE

  datasource:
    url: jdbc:postgresql://postgre-db:5432/taskflow
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
