package taskflowapi.domain.enums;

public enum EDepartamento {

    DESENVOLVIMENTO,
    RECURSOS_HUMANOS,
    FINANCAS,
    MARKETING,
    VENDAS,
    SUPORTE_AO_CLIENTE,
    OPERACOES,
    TECNOLOGIA_DA_INFORMACAO,
    PESQUISA_E_DESENVOLVIMENTO,
    LOGISTICA,
    QUALIDADE,
    JURIDICO;
}
